# pyuic5 -x FinApp_v1.ui -o designer.py

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinApp_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
## Update designer file
from crypt_utils import update_UI
update_UI()

## Imports
from PyQt5 import QtCore, QtGui, QtWidgets
from designer import Ui_MainWindow
import sys
from data_utils import Database
from models.category import Category

def catch_exceptions(t, val, tb):
    QtWidgets.QMessageBox.critical(None,
                                   "An exception was raised",
                                   "Exception type: {}, Exception value: {}".format(t, val))
    old_hook(t, val, tb)


old_hook = sys.excepthook
sys.excepthook = catch_exceptions


class AppFin(Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.db = Database(db_name="finapp")

    def add_logging_func(self):
        self.passwordEdit.hide()
        self.loginEdit.hide()
        self.LogInButton.hide()
        # self.LogInButton.clicked.connect(self.login)
        # self.tabWidget.hide()

    def set_addExpense_UI(self):
        self.expenseDateEdit.setCalendarPopup(True)
        self.expenseDateEdit.setDateTime(QtCore.QDateTime.currentDateTime())

    def set_AddCategory_UI(self):
        self.addCategoryButton.clicked.connect(self.add_new_category)
        self.categoryListViewModel = QtGui.QStandardItemModel()
        self.categoriesListView.setModel(self.categoryListViewModel)
        for i in self.db.get_categories():
            item = QtGui.QStandardItem(i)
            self.categoryListViewModel.appendRow(item)
        self.deleteCategoryButton.clicked.connect(self.delete_category)

    def login(self):
        if self.loginEdit.toPlainText() == "dan" and self.passwordEdit.toPlainText() == "dan":
            self.passwordEdit.hide()
            self.loginEdit.hide()
            self.LogInButton.hide()
            self.tabWidget.show()

    def add_new_category(self):
        new_category = Category(self.categoryNameEdit.toPlainText())
        if new_category.name not in self.db.get_categories():
            self.db.add_category(new_category)
            item = QtGui.QStandardItem(new_category.name)
            self.categoryListViewModel.appendRow(item)
        else:
            print("Category exists already")

    def delete_category(self):
        selected_item = self.categoriesListView.selectedIndexes()[0]
        self.categoryListViewModel.removeRow(selected_item.row())
        self.db.remove_category(selected_item.data())


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    AppFin = AppFin()
    AppFin.setupUi(MainWindow)
    AppFin.add_logging_func()
    AppFin.set_addExpense_UI()
    AppFin.set_AddCategory_UI()
    MainWindow.show()
    sys.exit(app.exec_())
